#!/bin/bash


#/dev/sde2 /boot xfs rw,relatime,attr2,inode64,noquota 0 0
#/dev/sda1 / ext4 rw,relatime,data=ordered 0 0

infos=($(cat /etc/mtab|grep /dev/sd))

case ${infos[2]} in
        ext*)
		e2label ${infos[0]} ceres_sys
		;;
        xfs)
		xfs_admin -L ceres_sys ${infos[0]}
		;;
esac

rm /var/fm/.blkid.txt 2>/dev/null
